services:
  omar:
    build: .
    ports:
      - "8080:8080"
    environment:
      Instance: 1
      SPRING_DATA_MONGODB_DATABASE: omar_52_1672
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017/?authSource=admin
    depends_on:
      - mongo


  elzaher:
    build: .
    ports:
      - "8081:8080"
    environment:
      Instance: 2
      SPRING_DATA_MONGODB_DATABASE: omar_52_1672
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017/omar_52_1672?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  nginx:
    image: nginx
    ports:
      - "1672:80"
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - omar
      - elzaher